services:
  timescaledb:
    image: timescale/timescaledb-postgis:latest-pg13
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - timescaledb

  fastapi-app:
    build:
      context: .
      dockerfile: timeseries_api/Dockerfile
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - timescaledb

volumes:
  db_data: